#  启动命令  docker-compose up  （-d可以后台运行）docker-compose up  xx-service 可以指定启动某一个应用
#  停止命令  docker-compose up
version: '2'

services:
  eureka-service:
    image: hub.audi.com:1010/micro-service/eureka-service:latest
    ports:
      - 8761:8761
    volumes:
      - /Users/wangquanzhou/IdeaProjects/micro-service/log_docker:/log

  infrastructure-service:
    image: hub.audi.com:1010/micro-service/infrastructure-service:latest
    links:
      - eureka-service
    ports:
      - 9090:9090
    volumes:
      - /Users/wangquanzhou/IdeaProjects/micro-service/log_docker:/log

  user-service:
    image: hub.audi.com:1010/micro-service/user-service:latest
    links:
      - eureka-service
      - infrastructure-service
    ports:
      - 8080:8080
    volumes:
      - /Users/wangquanzhou/IdeaProjects/micro-service/log_docker:/log

  zuul-service:
    image: hub.audi.com:1010/micro-service/zuul-service:latest
    links:
      - eureka-service
      - user-service
      - infrastructure-service
    ports:
      - 7070:7070
    volumes:
      - /Users/wangquanzhou/IdeaProjects/micro-service/log_docker:/log