#  启动命令  docker-compose up  （-d可以后台运行）docker-compose up  xx-service 可以指定启动某一个应用
#  停止命令  docker-compose up
version: '2'

services:
  eureka-service:
    image: hub.audi.com:1010/micro-service/eureka-service:latest
    ports:
      - 8761:8761
    volumes:
      - /Users/wangquanzhou/IdeaProjects/micro-service/log_docker:/log

  infrastructure-service:
    image: hub.audi.com:1010/micro-service/infrastructure-service:latest
    links:
      - eureka-service
    ports:
      - 5060:5060
    volumes:
      - /Users/wangquanzhou/IdeaProjects/micro-service/log_docker:/log

  user-service:
    image: hub.audi.com:1010/micro-service/user-service:latest
    links:
      - eureka-service
      - infrastructure-service
    ports:
      - 5070:5070
    volumes:
      - /Users/wangquanzhou/IdeaProjects/micro-service/log_docker:/log

  gateway-service:
    image: hub.audi.com:1010/micro-service/gateway-service:latest
    links:
      - eureka-service
      - user-service
      - infrastructure-service
    ports:
      - 5040:5040
    volumes:
      - /Users/wangquanzhou/IdeaProjects/micro-service/log_docker:/log