spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: infrastructure-service
          uri: lb://infrastructure
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=1
  redis:
    host: 192.168.199.219
    database: 0
    port: 6378

#  配置日志
logging:
  config: classpath:logback-gateway.xml