version: "3.4"
services:
  eureka-service:
    image: hub.audi.com:1010/micro-service/eureka-service:latest
    deploy:
      endpoint_mode: vip
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "300M"
    ports:
      - "8761:8761"
    environment:
      - "constraint node.labels.func == master"


  infrastructure:
    image: hub.audi.com:1010/micro-service/infrastructure-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: "300M"
    depends_on:
      - eureka-service
    ports:
      - "5060:5060"

  gateway:
    image: hub.audi.com:1010/micro-service/gateway-service:latest
    deploy:
      endpoint_mode: vip
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "300M"
    depends_on:
      - eureka-service
      - infrastructure
      - user
    ports:
      - "5040:5040"
    environment:
      - "constraint node.labels.func == master"

  user:
    image: hub.audi.com:1010/micro-service/user-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "300M"
    depends_on:
      - eureka-service
      - infrastructure
    ports:
      - "5070:5070"


networks:
  default:
    external:
      name: my_net