version: "3.4"
services:
  eureka-service:
    image: registry.cn-shanghai.aliyuncs.com/audi_micro_service/micro-service/eureka-service:latest
    deploy:
      endpoint_mode: vip
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "300M"
    ports:
      - "8761:8761"


  infrastructure:
    image: registry.cn-shanghai.aliyuncs.com/audi_micro_service/micro-service/infrastructure-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: "300M"
    depends_on:
      - eureka-service

  gateway:
    image: registry.cn-shanghai.aliyuncs.com/audi_micro_service/micro-service/gateway-service:latest
    deploy:
      endpoint_mode: vip
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "300M"
    depends_on:
      - eureka-service
      - infrastructure
      - user
    ports:
      - "5040:5040"

  user:
    image: registry.cn-shanghai.aliyuncs.com/audi_micro_service/micro-service/user-service:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "300M"
    depends_on:
      - eureka-service
      - infrastructure


networks:
  default:
    external:
      name: my-net